spring.application.name=team-task-manager

# MongoDB
spring.data.mongodb.uri=${MONGO_URI}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Server
server.port=${PORT:8080}

# CORS
cors.allowed.origins=${CORS_ORIGINS:*}